### ISSUE TITLE
New role: Enforcer

### ISSUE THREAD

**Issue by Hunter0035** [fetlife/glossary#16]
I was thinking,

A dom friend of mine works a lot, and i have a past with a new sub of his, he asked me if id go over and tie her up just befire he finishes work so he can come over and make her enjoy the cnc fetish of hers.

It made me think, we should have a role that is someone who enjoys prepping a sub for a dom/domme, for some reason it is exhilirsting to me to keep someone going or tie them up for someone else, keeping them going with any way from basic to advanced.

Fetlife user: VenomousVeins

**Comment by johnbaku** [comment]
Interesting idea, but I am not sure that enforcer is the write word to describe what you are referring to though.

Here is the definition of enforcer:

<img width="484" alt="dictionary__16_found_" src="https://user-images.githubusercontent.com/22100/32856805-bd4c861c-c9fa-11e7-9918-9fc6f8665a8f.png">

**Comment by Ticklee1** [comment]
Part of this sounds kind of like a "fluffer", which is someone who job it is to get a male pornstar hard and keep him hard before a scene.  (It's actually considered to be part of the make-up department.)  Maybe your term would be "rigger-fluffer" -- One who ties up the sub and then warms them up in preparation for the Top.

**Comment by wickedthisway** [comment]
A few suggestions for you. 
INTRANSITIVE/TRANSITIVE if an event or situation warms up, or if something warms it up, it starts to become enjoyable, interesting, or busy
TRANSITIVE if a minor performer warms up an audience, they put the audience in the right mood for the main performance. 

Provisioner/provisioness
Coddler
Trusser
Livery
Mufter
Tailor/Taillair
Contriver/contrivess
