### ISSUE TITLE
Hotwife/Cuckoldress Differentiation

### ISSUE THREAD

**Issue by DWMDomSFbay** [fetlife/glossary#22]
I would like to suggest that the characteristics of Hotwife and Cuckolderess should be differentiated, currently they both are:

A married woman who may pursue sexual relationships with men other than her husband, oftentimes to humiliate or degrade him. Her husband has full knowledge of her activities and consents to them.

Here are my suggestions:

Hotwife A married woman who pursues sexual relationships with men other than her husband, Her husband has full knowledge of her activities and consents to them and gets pleasure from them.

Cuckoldress A woman who may pursues sexual relationships with other people than her partner, oftentimes she is sexually dominant to her partner and her outside play is to reinforce her dominance and oftentimes to humiliate or degrade her partner, Her partner has full knowledge of her activities.

Having been around the 'alternative' sexual lifestyles for a long time now and talking to couple, there is a   notable difference between a wife who she and her partner both want her to have sex with other men, but there is not humiliation or power exchange between them, this is what I see a 'hotwife' to be. A cuckoldress is a wife that displays sexual dominance over her partner and exercises that dominance to the point of having sexual relationships outside of their relationship, that may involve the partners humiliation or degradation.

**Comment by PilarPalabundar** [comment]
Agreed. This is an incorrect definition of HotWife.

**Comment by johnbaku** [comment]
@DWMDomSFbay thanks! Great catch. Fixed the issues with PR #46. 

Note: I made some grammatical changes and removed a small part of it. Not sure it was the 100% right decision but it felt right at the time.
