### ISSUE TITLE
Request for role: Feminizer

### ISSUE THREAD

**Issue by TRmtd** [fetlife/glossary#48]
Please add "Feminizer" and associated D/s relationships to Fetlife. A Feminizer's role is to transform men into feminine beings by modifying their appearance, behavior and mindset.

The suggestion is currently ranked 16th with over 2,600 votes: https://fetlife.com/improvements/13663

Role: Feminizer
D/s: Feminized by "user"
D/s: Feminizing "user"

Some of the most popular Fetlife users in the trans/cdtv/sissy scene are Feminizers. We are the counterpart to these demographics, but Fetlife currently does not provide an appropriate role.

Thank you,
MTD

**Comment by johnbaku** [comment]
Really appreciate the initiative and good catch!

I'm a bit on the fence where exactly they fit on the respective lists... this is where I have them currently... how do they look?

<img width="1383" alt="Screen Shot 2020-01-27 at 10 48 20 AM" src="https://user-images.githubusercontent.com/22100/73205057-0e577800-40f5-11ea-8fee-801d89492e99.png">

<img width="1383" alt="Screen Shot 2020-01-27 at 10 51 20 AM" src="https://user-images.githubusercontent.com/22100/73205058-0e577800-40f5-11ea-9850-696c5149803b.png">

*P.S. Feature spec has been written up and shared with the product team.*

**Comment by TRmtd** [comment]
Before "sissy" would indeed be appropriate for the role.  The "feminizing" and "feminized by" would be more appropriate before "Keyholder, Chastity", but that's really splitting hairs.  Either way works.  

Thank you for your consideration!

**Comment by johnbaku** [comment]
@TRmtd I'm torn as well. The reason I choose to add it after "Cuckquean" is so that it's consistent with the Roles list i.e. after "Cuckquean" in both lists hence making it more likely easier to find... I believe.

Having said that, there is not much consistency with the two lists and probably could use a bit of a clean-up. My main priority is making it easy for people to find.

**Comment by TRmtd** [comment]
@johnbaku : Consistency definitely makes sense. :+1:

**Comment by nielsenramon** [comment]
The roles and D/s relationship types have been added! You can now add them to your profile 🥳

**Comment by TRmtd** [comment]
@jonhbaku & @nielsenramon:  As always, Fetlife is ahead of the curve.  Thanks guys! :+1:

**Comment by TRmtd** [comment]
@johnbaku & @nielsenramon:  The Android app is using an improper preposition for the D/s relationship.  Instead of "Feminized by", it's using "Feminized of": https://fetlife.com/users/9614935

Also, can we please have "Feminizer" added to the glossary: https://fetlife.com/glossary

Thank you!

**Comment by johnbaku** [comment]
@TRmtd said:

> The Android app is using an improper preposition for the D/s relationship. Instead of "Feminized by", it's using "Feminized of"

Does it say "of" in the Android app and "by" on the website? P.S. For me, I see by on the website.

Also, in the pulldown menu it says "by" here:

<img width="500" alt="Screen Shot 2020-01-29 at 10 39 44 AM" src="https://user-images.githubusercontent.com/22100/73386420-aaaf8500-4283-11ea-9f47-e2ca4277ff3f.png">

> Also, can we please have "Feminizer" added to the glossary: https://fetlife.com/glossary

By any chance are you familiar with how to create a PR? If so, mind creating a PR and adding the definition. Otherwise, suggest a definition to me and I can create a PR for it!

**Comment by johnbaku** [comment]
@nielsenramon is is just me or the label spacing seems off? 

This is our normal spacing:

<img width="487" alt="Screen Shot 2020-01-29 at 10 42 53 AM" src="https://user-images.githubusercontent.com/22100/73386676-1b56a180-4284-11ea-8a2d-1d55689b5543.png">

Argh... I'll create a bug report!

**Comment by TRmtd** [comment]
@johnbaku:  Yes.  The website says "by" and the Android app says "for".

I don't know what a PR is, John.   Here's a definition for Feminizer:
A Feminizer's role is to transform men into feminine beings by modifying their appearance, behavior and mindset.

**Comment by TRmtd** [comment]
@johnbaku:  My bad, the Android app says "of".  It should be "by".

**Comment by johnbaku** [comment]
@TRmtd suggested the definition here #49. Just waiting for a couple people to review as a sanity check and then once reviewed it will be merged and viewable on FetLife.

**Comment by nielsenramon** [comment]
FYI: Fixed the spacing issue :D

**Comment by johnbaku** [comment]
@TRmtd unfortunately at this time I don't know if we can or will update the Android app. It's not being actively maintained. :-/

**Comment by TRmtd** [comment]
> @TRmtd suggested the definition here #49. Just waiting for a couple people to review as a sanity check and then once reviewed it will be merged and viewable on FetLife.

Hi John, The definition seems to have been reviewed, but it was never added to the glossary: https://fetlife.com/glossary

**Comment by johnbaku** [comment]
@TRmtd good catch!

@nielsenramon or a @fetlife/caretakers can you please create a bug so we can look into why even though #49 has been merged it's not appearing in our glossary? Thanks.

**Comment by JSFernandes** [comment]
Hey everyone

It looks like the issue with the glossary not updating automatically has been ongoing for a long time. The fix is now headed to production.

I have already tried this fix in staging. Since it shares uses the same database as production, feminizer is now showing up in the glossary.

**Comment by TRmtd** [comment]
@JSFernandes & @johnbaku:  Thanks guys!  The definition is in the glossary now.  I appreciate your time and efforts!  

Best,
MTD
