### ISSUE TITLE
Partners - D/s

### ISSUE THREAD

**Issue by Hanjalina** [fetlife/glossary#54]
Partners in a play or session environment where one is a dominant and the other is a submissive who is usually assisting the Dominant

**Comment by johnbaku** [comment]
Hey @Hanjalina, 

Just trying to understand, are you recommending a new type of D/s relationship? Or... yeah... not sure I understand.

**Comment by Hanjalina** [comment]
Yes.  Another option to choose from.  There are a few of FL I team up with - usually with me as the Dominant, with a sub assistant, but there have been times I have double teamed a sub with another Domme or Dom.  I would like to add them to my relationships, but there is nothing even remotely close!  

I was completely thrown off guard being directed here to submit a suggestion; did I do it incorrectly?

**Comment by johnbaku** [comment]
@Hanjalina asked:

> I was completely thrown off guard being directed here to submit a suggestion; did I do it incorrectly?

No, not... it's all good. It was just not clear what it was. I will update the title.

**Comment by Hanjalina** [comment]
Thanks John!
